"""Run, facing right like the walk: an easy gallop, 12 frames, 2 px of travel per frame.

Each leg has twelve hand-typed drawings in the walk's format (13 columns, pivot at
column 6, 'B' coat, 'P' paw), indexed from that leg's touchdown. Hinds land first,
the far hind a frame after the near; the fores land four frames later with the
same one-frame stagger. Frames 9-11 are the gathered flight with every leg under
the body.

Stance drawings (k0-k2) are anchored on the ground row and planted paws move back
2 px a frame, which with 'travel': 2 holds them still on the page. Swing drawings
hang from the hip or shoulder and ride the body's bob."""
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), 'kit'))
from catkit import GROUND, build, check, rows_mask, spans, walk  # noqa: E402

TRAVEL = 2
N = 12
HIP, SHOULDER = walk.HIP, walk.SHOULDER
HIND_TOP, FORE_TOP = walk.HIND_TOP, walk.FORE_TOP
STANCE = 3


def _d(s):
    rs = s.strip('\n').split('\n')
    assert all(len(r) == 13 for r in rs), rs
    return rs


HIND = [_d(s) for s in ('''
......BBB....
......BBB....
.....BBB.....
....BBB......
.....BB......
......BB.....
.......PP....
.......PPP...
''', '''
......BBB....
.....BBB.....
....BBB......
...BBB.......
....BB.......
.....PP......
.....PPP.....
''', '''
.....BBB.....
....BBB......
...BBB.......
..BBB........
.BBB.........
..BB.........
...PP........
...PPP.......
''', '''
.....BBB.....
....BBB......
...BBB.......
.BBB.........
BBP..........
PP...........
''', '''
.....BBB.....
...BBBB......
.BBBB........
.BBPP........
..PP.........
''', '''
.....BBB.....
....BBB......
..BBBB.......
..BBPP.......
...PP........
''', '''
.....BBB.....
....BBBB.....
....BBB......
....BBB......
.....BPP.....
......PP.....
''', '''
......BBB....
.....BBBB....
.....BBB.....
......BBB....
.......BP....
.......PPP...
''', '''
......BBB....
......BBBB...
.......BBB...
........BBB..
.........BB..
.........PPP.
''', '''
......BBB....
.......BBB...
........BBB..
.......BBB...
........BB...
.........BB..
.........PPP.
''', '''
......BBB....
......BBB....
.......BBB...
......BBB....
.......BB....
.......BB....
........PP...
........PPP..
''', '''
......BBB....
......BBB....
.....BBB.....
.....BBB.....
......BB.....
.......BB....
.......PP....
.......PPP...
''')]

FORE = [_d(s) for s in ('''
...BBBBB.....
...BBBB......
....BBB......
.....BBB.....
.....BBB.....
......BBB....
......BB.....
.......PP....
.......PPP...
''', '''
...BBBBB.....
...BBBB......
....BBB......
....BBB......
....BBB......
.....BB......
.....PP......
.....PPP.....
''', '''
...BBBBB.....
...BBBB......
...BBB.......
...BBB.......
..BBB........
..BBB........
..BB.........
...PP........
...PPP.......
''', '''
...BBBBB.....
...BBBB......
..BBB........
..BB.........
.BB..........
.PP..........
PP...........
''', '''
...BBBBB.....
...BBBB......
...BBB.......
...BBB.......
..BBB........
.PPB.........
PP...........
''', '''
...BBBBB.....
...BBBB......
....BBB......
....BBB......
....BB.......
...PP........
..PP.........
''', '''
...BBBBB.....
...BBBBB.....
....BBBB.....
.....BBB.....
......BB.....
......PP.....
.....PP......
''', '''
...BBBBB.....
....BBBB.....
.....BBB.....
......BBB....
.......BB....
........PPP..
''', '''
...BBBBB.....
...BBBBBBB...
.....BBBBBB..
........BBB..
.........BB..
.........PPP.
''', '''
...BBBBB.....
...BBBBBBB...
.....BBBBBB..
.......BBBBB.
.........BBB.
..........PP.
..........PPP
''', '''
...BBBBB.....
...BBBBBB....
....BBBBBB...
......BBBB...
.......BBB...
........BB...
........PP...
........PPP..
''', '''
...BBBBB.....
...BBBB......
....BBB......
.....BBB.....
.....BBB.....
......BBB....
......BB.....
.......PP....
''')]

# Touchdown frame of each leg, and its pivot column.
LAND = {'NH': 0, 'FH': 1, 'NF': 5, 'FF': 6}
PIVOT = {'NH': HIP, 'FH': HIP + 1, 'NF': SHOULDER, 'FF': SHOULDER + 1}
# Body bob: low on each pair's middle stance, high in the gathered flight.
DY = [0, 1, 0, -1, -1, 0, 1, 0, -1, -1, -2, -1]

# Spine: stretched out while the hinds push and the fores reach (2-5), arched and
# short in the gathered flight (8-11, 0), the walk's own body between.
BODIES = {
    'mid': walk.BODY,
    'ext': rows_mask({11: (17, 21), 12: (8, 22), 13: (6, 23), 14: (5, 24), 15: (5, 25), 16: (5, 25),
                      17: (5, 26), 18: (5, 25), 19: (6, 25), 20: (7, 24), 21: (9, 23)}),
    'gath': rows_mask({10: (13, 19), 11: (9, 21), 12: (7, 22), 13: (7, 23), 14: (7, 24), 15: (7, 24),
                       16: (7, 24), 17: (7, 24), 18: (7, 23), 19: (8, 23), 20: (9, 22), 21: (11, 21)}),
}
SPINE = ['gath', 'mid', 'ext', 'ext', 'ext', 'ext', 'mid', 'mid', 'gath', 'gath', 'gath', 'gath']
# Near haunch follows the near hind: forward on the reach, back on the push.
HAUNCH_K = ['fwd', 'mid', 'back', 'back', 'back', 'mid', 'mid', 'fwd', 'fwd', 'fwd', 'fwd', 'fwd']
# The walk's raised tail carried lower and further back, rising and falling
# against the bob.
TAILS = {
    'lo': [(8, 14), (5, 13), (3, 11), (2, 8), (3, 5)],
    'mid': [(8, 13), (5, 12), (3, 10), (2, 7), (3, 4)],
    'hi': [(8, 13), (5, 11), (3, 9), (3, 6), (5, 3)],
}
TAIL_SEQ = ['mid', 'lo', 'lo', 'mid', 'mid', 'hi', 'hi', 'mid', 'lo', 'lo', 'mid', 'hi']


def k_of(leg, f):
    return (f - LAND[leg]) % N


def leg_layer(leg, f):
    k = k_of(leg, f)
    draw = HIND[k] if leg[1] == 'H' else FORE[k]
    if k < STANCE:
        top = GROUND - len(draw) + 1
    else:
        top = (HIND_TOP if leg[1] == 'H' else FORE_TOP) + DY[f]
    near = leg[0] == 'N'
    rs = [r.replace('B', 'n' if near else 'f').replace('P', 'p' if near else 'q') for r in draw]
    return (rs, PIVOT[leg] - 6, top)


def shifted(mask, dy):
    return {(x, y + dy) for (x, y) in mask}


def mask_codes(mask, c):
    return spans({y: [(x, x) for (x, yy) in mask if yy == y] for y in {y for _, y in mask}}, c)


def pose(f):
    dy = DY[f]
    tail = walk.tail_px(TAILS[TAIL_SEQ[f]], dy)
    tail_rows = [['.'] * 32 for _ in range(32)]
    for (x, y), c in tail.items():
        tail_rows[y][x] = 't' if c == 'B' else c
    top = 12 + dy
    haunch = rows_mask({top + j: s for j, s in walk.HAUNCH[HAUNCH_K[k_of('NH', f)]].items()})
    lay = [leg_layer('FH', f), leg_layer('FF', f), ([''.join(r) for r in tail_rows], 0, 0),
           mask_codes(shifted(BODIES[SPINE[f]], dy), 'b'), mask_codes(shifted(walk.BIB, dy), 'W'),
           leg_layer('NH', f), mask_codes(haunch, 'h'), leg_layer('NF', f)]
    head = [''.join(walk.HEAD.get((x, y), '.') for x in range(13)) for y in range(11)]
    return build(lay, heads=[(head, walk.HEAD_X, walk.HEAD_Y + 1 + dy)])


def check_planting():
    for leg in LAND:
        xs = []
        for f in range(N):
            k = k_of(leg, f)
            if k < STANCE:
                draw = HIND[k] if leg[1] == 'H' else FORE[k]
                xs.append((k, PIVOT[leg] - 6 + draw[-1].index('P')))
        xs.sort()
        assert all(a[1] - b[1] == TRAVEL for a, b in zip(xs, xs[1:])), (leg, xs)


check_planting()
CLIP = check({'loop': True, 'travel': TRAVEL,
              'frames': [{'ms': 75, 'px': pose(f)} for f in range(N)]}, 'run')
