"""Swat, facing left: from the sit the near foreleg cocks up beside the face, whips
forward and down past the chin, follows through low, and folds back to the sit.
Uses the groom clip's body (far foreleg carrying the chest) and its lift/chest
drawings for the way up and down."""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path[:0] = [os.path.join(HERE, 'kit'), HERE]
from catkit import check, frag, SIT  # noqa: E402
import groom  # noqa: E402

# n coat, p paw. The paw is the leading edge on every drawing.
COCK = (frag('''
.ppp.........
pppp.........
.nnn.........
.nnn.........
.nnn.........
..nnn........
..nnn........
...nnnn......
...nnnnnn....
....nnnnnn...
.....nnnn....
'''), 1, 9)
# Arm straight out at chin height: upper arm forward from the shoulder,
# forearm level, paw turned down.
SWIPE = (frag('''
....nnnnn....
ppnnnnnnnn...
pp.nnnnnnn...
.....nnnn....
'''), 1, 16)
FOLLOW = (frag('''
.....nnnn....
....nnnn.....
...nnnn......
..nnn........
.nnn.........
ppn..........
pp...........
'''), 1, 18)

# Motion marks along the paw's path, drawn after the outline.
ARC = {(2, 12), (1, 14), (1, 15)}
ARC_LOW = {(1, 20), (1, 21)}


def marks(px, pts):
    g = [list(r) for r in px]
    for x, y in pts:
        if g[y][x] == '.':
            g[y][x] = 'X'
    return [''.join(r) for r in g]


FRAMES = [
    (350, SIT),
    (100, groom.frame('lift', 0)),
    (110, groom.frame(COCK, 0)),
    (60, marks(groom.frame(SWIPE, 0), ARC)),
    (90, marks(groom.frame(FOLLOW, 0), ARC_LOW)),
    (130, groom.frame('chest', 0)),
    (100, groom.frame('lift', 0)),
    (300, SIT),
]

CLIP = check({'loop': False, 'frames': [{'ms': ms, 'px': px} for ms, px in FRAMES]}, 'swat')
