"""Hand-drawn leg drawings for the sleek cat walking right.

Every drawing is 13 columns wide; column 6 is the pivot (hip for HIND, shoulder for
FORE). 'B' coat, 'P' paw. HIND drawings start at row HIND_TOP and show only the leg
below the haunch; the haunch itself is one of three hand-drawn masses in walk.py,
picked per drawing. FORE drawings start at FORE_TOP with the upper arm tucked into
the chest and the elbow showing at the back.

Stance drawings s+3..s-3 are named for where the planted paw sits: its ground row
covers pivot+r-1 .. pivot+r+1, so consecutive stance drawings move the paw back one
pixel, matching TRAVEL. Swing drawings w-3..w+3 are off the ground; the swing
covers most of its distance in the middle three frames (w-1, w+1, w+3h) and then
sets the paw down from w+3, so on the "up" frames the swinging leg is already well
ahead of the planted one instead of crossing it.

Hind: stifle at the front under the haunch, shin running back-down to the hock (the
back edge's farthest-back point, three rows above the toes), then the rear foot
running forward-down to the toes. Fore: elbow at the back, straight forearm, wrist,
paw; in swing the wrist folds so the paw trails pad-back, then unfolds to reach."""

HIND_TOP = 22
FORE_TOP = 21


def _d(s):
    rows = s.strip('\n').split('\n')
    assert all(len(r) == 13 for r in rows), rows
    return rows


HIND = {
    's+3': _d('''
........BBB..
.......BBB...
.......BB....
......BBB....
.......BB....
.......BB....
........PP...
........PPP..
'''),
    's+2': _d('''
.......BBB...
......BBB....
......BB.....
.....BBB.....
......BB.....
......BB.....
.......PP....
.......PPP...
'''),
    's+1': _d('''
......BBB....
.....BBB.....
.....BB......
....BBB......
.....BB......
.....BB......
......PP.....
......PPP....
'''),
    's0': _d('''
......BBB....
.....BBB.....
....BBB......
...BBB.......
....BB.......
....BB.......
.....PP......
.....PPP.....
'''),
    's-1': _d('''
.....BBB.....
....BBB......
...BBB.......
..BBB........
...BB........
...BB........
....PP.......
....PPP......
'''),
    's-2': _d('''
.....BBB.....
....BBB......
...BB........
.BBB.........
..BB.........
..BB.........
...PP........
...PPP.......
'''),
    's-3': _d('''
....BBB......
...BBB.......
.BBB.........
BBB..........
.BB..........
.BB..........
..PP.........
..PPP........
'''),
    'w-3': _d('''
....BBB......
...BBB.......
.BBB.........
BBB..........
.PP..........
.PP..........
'''),
    'w-1': _d('''
......BBB....
.....BBB.....
....BBB......
....BBB......
.....PPP.....
'''),
    'w+1': _d('''
.......BBB...
......BBB....
......BB.....
.....BBB.....
......BB.....
......PPP....
'''),
    'w+3h': _d('''
........BBB..
.......BBB...
.......BB....
......BBB....
.......BB....
........PPP..
'''),
    'w+3': _d('''
........BBB..
.......BBB...
.......BB....
......BBB....
.......BB....
........PP...
........PPP..
'''),
}

FORE = {
    's+3': _d('''
....BBBB.....
....BBBBB....
.....BBBB....
......BBB....
......BBB....
.......BBB...
........BB...
........PP...
........PPP..
'''),
    's+2': _d('''
....BBBB.....
....BBBB.....
.....BBB.....
.....BBB.....
......BBB....
......BBB....
.......BB....
.......PP....
.......PPP...
'''),
    's+1': _d('''
...BBBBB.....
...BBBB......
....BBB......
....BBB......
.....BBB.....
.....BBB.....
......BB.....
......PP.....
......PPP....
'''),
    's0': _d('''
...BBBBB.....
...BBBB......
....BBB......
....BBB......
....BBB......
....BBB......
.....BB......
.....PP......
.....PPP.....
'''),
    's-1': _d('''
...BBBBB.....
...BBBB......
...BBB.......
...BBB.......
...BBB.......
...BBB.......
....BB.......
....PP.......
....PPP......
'''),
    's-2': _d('''
...BBBBB.....
...BBBB......
...BBB.......
..BBB........
..BBB........
..BBB........
..BBB........
...PP........
...PPP.......
'''),
    's-3': _d('''
...BBBBB.....
...BBBB......
..BBB........
..BBB........
.BBB.........
.BB..........
.BB..........
..PP.........
..PPP........
'''),
    'w-3': _d('''
...BBBBB.....
...BBBB......
..BBB........
..BB.........
.BB..........
.PP..........
PP...........
'''),
    'w-1': _d('''
...BBBBB.....
...BBBB......
....BBB......
....BB.......
.....BB......
....PP.......
...PP........
'''),
    'w+1': _d('''
...BBBBB.....
...BBBBB.....
....BBBB.....
.....BBB.....
......BB.....
......PP.....
.....PP......
'''),
    'w+3h': _d('''
...BBBBB.....
....BBBB.....
.....BBB.....
......BBB....
.......BB....
........PPP..
'''),
    'w+3': _d('''
....BBBB.....
....BBBBB....
.....BBBB....
......BBB....
.......BB....
.......BB....
........PPP..
'''),
}
